// Generated by CoffeeScript 2.4.1
var draw, setup;

setup = function() {
  return createCanvas(200, 200);
};

draw = function() {
  return bg(0.5);
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUEsSUFBQSxFQUFBOztBQUFBLEtBQUEsR0FBUSxRQUFBLENBQUEsQ0FBQTtTQUNQLFlBQUEsQ0FBYSxHQUFiLEVBQWlCLEdBQWpCO0FBRE87O0FBRVIsSUFBQSxHQUFPLFFBQUEsQ0FBQSxDQUFBO1NBQ04sRUFBQSxDQUFHLEdBQUg7QUFETSIsInNvdXJjZXNDb250ZW50IjpbInNldHVwID0gLT5cclxuXHRjcmVhdGVDYW52YXMgMjAwLDIwMFxyXG5kcmF3ID0gLT5cclxuXHRiZyAwLjUiXX0=
//# sourceURL=c:\github\000-Mall\coffee\sketch.coffee